log_level: INFO
service:
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/storage/snapshots
  on_disk_payload: true
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
cluster:
  enabled: false
telemetry_disabled: true
